name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 18.x
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build
      - name: Create env file
          run: |
            touch .env
            echo REACT_APP_STRIPE_KEY=${{ secrets.REACT_APP_STRIPE_KEY }} >> .env
            cat .env

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADVO_ALUMNI }}'
          channelId: live
          projectId: advo-alumni
